import shirtImage1 from "../assets/product-shirt-1.jpg";
import shirtImage2 from "../assets/product-shirt-2.jpg";
import tshirtImage1 from "../assets/product-tshirt-1.jpg";
import tshirtImage2 from "../assets/product-tshirt-2.jpg";
import trouserImage1 from "../assets/product-trouser-1.jpg";
import trouserImage2 from "../assets/product-trouser-2.jpg";
import suitImage1 from "../assets/product-suit-1.jpg";
import suitImage2 from "../assets/product-suit-2.jpg";

export const products = [
  // Shirts (10 products)
  {
    id: "shirt-1",
    name: "Classic White Formal Shirt",
    category: "Shirts",
    price: 89,
    discountPrice: 69,
    rating: 4.8,
    sizeOptions: ["S", "M", "L", "XL", "XXL"],
    colorOptions: ["White", "Light Blue", "Pink"],
    fabric: "100% Premium Cotton",
    fitType: "Slim Fit",
    description:
      "Timeless white formal shirt crafted from premium cotton. Perfect for business meetings and formal occasions.",
    image: shirtImage1,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "2-3 business days",
  },
  {
    id: "shirt-2",
    name: "Navy Blue Business Shirt",
    category: "Shirts",
    price: 95,
    rating: 4.7,
    sizeOptions: ["S", "M", "L", "XL"],
    colorOptions: ["Navy", "Black", "Charcoal"],
    fabric: "Cotton Blend",
    fitType: "Regular Fit",
    description:
      "Sophisticated navy blue shirt with a modern cut. Ideal for professional settings.",
    image: shirtImage2,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "2-3 business days",
  },
  {
    id: "shirt-3",
    name: "Light Blue Oxford Shirt",
    category: "Shirts",
    price: 79,
    discountPrice: 59,
    rating: 4.6,
    sizeOptions: ["M", "L", "XL", "XXL"],
    colorOptions: ["Light Blue", "White", "Pink"],
    fabric: "Oxford Cotton",
    fitType: "Slim Fit",
    description:
      "Classic oxford shirt in light blue. Versatile and comfortable for everyday wear.",
    image: shirtImage1,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "3-4 business days",
  },
  {
    id: "shirt-4",
    name: "Black Formal Dress Shirt",
    category: "Shirts",
    price: 99,
    rating: 4.9,
    sizeOptions: ["S", "M", "L", "XL", "XXL"],
    colorOptions: ["Black", "White", "Navy"],
    fabric: "Premium Cotton",
    fitType: "Slim Fit",
    description:
      "Elegant black formal shirt for special occasions and evening events.",
    image: shirtImage2,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "2-3 business days",
  },
  {
    id: "shirt-5",
    name: "Checked Casual Shirt",
    category: "Shirts",
    price: 69,
    rating: 4.5,
    sizeOptions: ["M", "L", "XL"],
    colorOptions: ["Blue Check", "Red Check", "Green Check"],
    fabric: "Cotton Flannel",
    fitType: "Regular Fit",
    description:
      "Casual checked shirt perfect for weekend outings and relaxed settings.",
    image: shirtImage1,
    stockStatus: "Low Stock",
    brand: "MenStyle",
    deliveryTime: "3-5 business days",
  },
  {
    id: "shirt-6",
    name: "Striped Business Shirt",
    category: "Shirts",
    price: 85,
    discountPrice: 65,
    rating: 4.7,
    sizeOptions: ["S", "M", "L", "XL"],
    colorOptions: ["Blue Stripe", "Pink Stripe", "Gray Stripe"],
    fabric: "Cotton Blend",
    fitType: "Slim Fit",
    description:
      "Modern striped shirt for a contemporary business look.",
    image: shirtImage2,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "2-3 business days",
  },
  {
    id: "shirt-7",
    name: "White Linen Shirt",
    category: "Shirts",
    price: 109,
    rating: 4.8,
    sizeOptions: ["M", "L", "XL", "XXL"],
    colorOptions: ["White", "Beige", "Light Gray"],
    fabric: "100% Linen",
    fitType: "Regular Fit",
    description:
      "Breathable linen shirt perfect for summer and casual occasions.",
    image: shirtImage1,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "2-3 business days",
  },
  {
    id: "shirt-8",
    name: "Charcoal Gray Shirt",
    category: "Shirts",
    price: 92,
    rating: 4.6,
    sizeOptions: ["S", "M", "L", "XL"],
    colorOptions: ["Charcoal", "Navy", "Black"],
    fabric: "Cotton Blend",
    fitType: "Slim Fit",
    description:
      "Versatile charcoal gray shirt suitable for both formal and casual wear.",
    image: shirtImage2,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "3-4 business days",
  },
  {
    id: "shirt-9",
    name: "Burgundy Formal Shirt",
    category: "Shirts",
    price: 88,
    discountPrice: 68,
    rating: 4.7,
    sizeOptions: ["M", "L", "XL"],
    colorOptions: ["Burgundy", "Wine", "Deep Red"],
    fabric: "Premium Cotton",
    fitType: "Slim Fit",
    description:
      "Bold burgundy shirt for making a statement at formal events.",
    image: shirtImage1,
    stockStatus: "Low Stock",
    brand: "MenStyle",
    deliveryTime: "3-5 business days",
  },
  {
    id: "shirt-10",
    name: "Cream Casual Shirt",
    category: "Shirts",
    price: 75,
    rating: 4.5,
    sizeOptions: ["S", "M", "L", "XL", "XXL"],
    colorOptions: ["Cream", "Beige", "Light Tan"],
    fabric: "Cotton",
    fitType: "Regular Fit",
    description:
      "Soft cream casual shirt for a relaxed and comfortable look.",
    image: shirtImage2,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "2-3 business days",
  },

  {
    id: "tshirt-1",
    name: "Classic Black T-Shirt",
    category: "T-Shirts",
    price: 29,
    discountPrice: 19,
    rating: 4.8,
    sizeOptions: ["S", "M", "L", "XL", "XXL"],
    colorOptions: ["Black", "White", "Gray"],
    fabric: "100% Cotton",
    fitType: "Regular Fit",
    description: "Essential black t-shirt. Soft, comfortable, and versatile for everyday wear.",
    image: tshirtImage1,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "2-3 business days",
  },
  {
    id: "tshirt-2",
    name: "Gray Basic Tee",
    category: "T-Shirts",
    price: 25,
    rating: 4.7,
    sizeOptions: ["S", "M", "L", "XL"],
    colorOptions: ["Gray", "Charcoal", "Light Gray"],
    fabric: "Cotton Blend",
    fitType: "Regular Fit",
    description: "Comfortable gray t-shirt perfect for casual outings.",
    image: tshirtImage2,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "2-3 business days",
  },
  {
    id: "tshirt-3",
    name: "White Premium Tee",
    category: "T-Shirts",
    price: 32,
    rating: 4.9,
    sizeOptions: ["M", "L", "XL", "XXL"],
    colorOptions: ["White", "Ivory", "Off-White"],
    fabric: "Premium Cotton",
    fitType: "Slim Fit",
    description: "High-quality white t-shirt with superior fabric and fit.",
    image: tshirtImage1,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "2-3 business days",
  },
  {
    id: "tshirt-4",
    name: "Navy V-Neck T-Shirt",
    category: "T-Shirts",
    price: 28,
    discountPrice: 22,
    rating: 4.6,
    sizeOptions: ["S", "M", "L", "XL"],
    colorOptions: ["Navy", "Black", "Gray"],
    fabric: "Cotton",
    fitType: "Regular Fit",
    description: "Classic v-neck tee in navy for a refined casual look.",
    image: tshirtImage2,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "3-4 business days",
  },
  {
    id: "tshirt-5",
    name: "Olive Green Tee",
    category: "T-Shirts",
    price: 30,
    rating: 4.5,
    sizeOptions: ["M", "L", "XL"],
    colorOptions: ["Olive", "Forest Green", "Sage"],
    fabric: "Cotton Blend",
    fitType: "Regular Fit",
    description: "Trendy olive green t-shirt for a modern casual wardrobe.",
    image: tshirtImage1,
    stockStatus: "Low Stock",
    brand: "MenStyle",
    deliveryTime: "3-5 business days",
  },
  {
    id: "tshirt-6",
    name: "Striped Casual Tee",
    category: "T-Shirts",
    price: 35,
    rating: 4.7,
    sizeOptions: ["S", "M", "L", "XL", "XXL"],
    colorOptions: ["Navy Stripe", "Gray Stripe", "Black Stripe"],
    fabric: "Cotton",
    fitType: "Regular Fit",
    description: "Classic striped t-shirt adding variety to your casual collection.",
    image: tshirtImage2,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "2-3 business days",
  },
  {
    id: "tshirt-7",
    name: "Burgundy Crew Neck",
    category: "T-Shirts",
    price: 27,
    discountPrice: 21,
    rating: 4.6,
    sizeOptions: ["M", "L", "XL"],
    colorOptions: ["Burgundy", "Wine", "Maroon"],
    fabric: "Cotton Blend",
    fitType: "Slim Fit",
    description: "Rich burgundy crew neck tee for a bold statement.",
    image: tshirtImage1,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "2-3 business days",
  },
  {
    id: "tshirt-8",
    name: "Charcoal Pocket Tee",
    category: "T-Shirts",
    price: 33,
    rating: 4.8,
    sizeOptions: ["S", "M", "L", "XL"],
    colorOptions: ["Charcoal", "Black", "Navy"],
    fabric: "Premium Cotton",
    fitType: "Regular Fit",
    description: "Stylish pocket tee in charcoal for added functionality and style.",
    image: tshirtImage2,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "3-4 business days",
  },
  {
    id: "tshirt-9",
    name: "Beige Minimalist Tee",
    category: "T-Shirts",
    price: 26,
    rating: 4.5,
    sizeOptions: ["M", "L", "XL", "XXL"],
    colorOptions: ["Beige", "Tan", "Sand"],
    fabric: "Cotton",
    fitType: "Regular Fit",
    description: "Minimalist beige t-shirt perfect for layering or standalone wear.",
    image: tshirtImage1,
    stockStatus: "Low Stock",
    brand: "MenStyle",
    deliveryTime: "3-5 business days",
  },
  {
    id: "tshirt-10",
    name: "Graphic Print Tee",
    category: "T-Shirts",
    price: 38,
    rating: 4.7,
    sizeOptions: ["S", "M", "L", "XL"],
    colorOptions: ["Black Print", "White Print", "Gray Print"],
    fabric: "Cotton Blend",
    fitType: "Regular Fit",
    description: "Trendy graphic print t-shirt for expressing your personal style.",
    image: tshirtImage2,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "2-3 business days",
  },

  // Trousers (10 products)
  {
    id: "trouser-1",
    name: "Navy Blue Chinos",
    category: "Trousers",
    price: 89,
    discountPrice: 69,
    rating: 4.8,
    sizeOptions: ["30", "32", "34", "36", "38"],
    colorOptions: ["Navy", "Black", "Khaki"],
    fabric: "Cotton Twill",
    fitType: "Slim Fit",
    description: "Classic navy chinos perfect for smart-casual occasions.",
    image: trouserImage1,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "2-3 business days",
  },
  {
    id: "trouser-2",
    name: "Beige Casual Pants",
    category: "Trousers",
    price: 79,
    rating: 4.7,
    sizeOptions: ["30", "32", "34", "36"],
    colorOptions: ["Beige", "Tan", "Stone"],
    fabric: "Cotton Blend",
    fitType: "Regular Fit",
    description: "Versatile beige pants ideal for casual and business-casual settings.",
    image: trouserImage2,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "2-3 business days",
  },
  {
    id: "trouser-3",
    name: "Black Dress Trousers",
    category: "Trousers",
    price: 99,
    rating: 4.9,
    sizeOptions: ["30", "32", "34", "36", "38"],
    colorOptions: ["Black", "Charcoal", "Navy"],
    fabric: "Wool Blend",
    fitType: "Slim Fit",
    description: "Elegant black dress trousers for formal occasions and business wear.",
    image: trouserImage1,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "2-3 business days",
  },
  {
    id: "trouser-4",
    name: "Gray Formal Pants",
    category: "Trousers",
    price: 92,
    discountPrice: 72,
    rating: 4.6,
    sizeOptions: ["32", "34", "36", "38"],
    colorOptions: ["Gray", "Charcoal", "Light Gray"],
    fabric: "Polyester Blend",
    fitType: "Regular Fit",
    description: "Professional gray formal pants suitable for office and meetings.",
    image: trouserImage2,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "3-4 business days",
  },
  {
    id: "trouser-5",
    name: "Khaki Cargo Pants",
    category: "Trousers",
    price: 75,
    rating: 4.5,
    sizeOptions: ["30", "32", "34", "36"],
    colorOptions: ["Khaki", "Olive", "Tan"],
    fabric: "Cotton",
    fitType: "Relaxed Fit",
    description: "Practical khaki cargo pants with multiple pockets for casual wear.",
    image: trouserImage1,
    stockStatus: "Low Stock",
    brand: "MenStyle",
    deliveryTime: "3-5 business days",
  },
  {
    id: "trouser-6",
    name: "Charcoal Dress Pants",
    category: "Trousers",
    price: 95,
    rating: 4.7,
    sizeOptions: ["30", "32", "34", "36", "38"],
    colorOptions: ["Charcoal", "Black", "Navy"],
    fabric: "Wool Blend",
    fitType: "Slim Fit",
    description: "Sophisticated charcoal dress pants for a polished appearance.",
    image: trouserImage2,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "2-3 business days",
  },
  {
    id: "trouser-7",
    name: "Olive Green Chinos",
    category: "Trousers",
    price: 82,
    discountPrice: 62,
    rating: 4.6,
    sizeOptions: ["32", "34", "36"],
    colorOptions: ["Olive", "Forest Green", "Khaki"],
    fabric: "Cotton Twill",
    fitType: "Slim Fit",
    description: "Stylish olive green chinos for a modern casual look.",
    image: trouserImage1,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "2-3 business days",
  },
  {
    id: "trouser-8",
    name: "Light Gray Trousers",
    category: "Trousers",
    price: 88,
    rating: 4.8,
    sizeOptions: ["30", "32", "34", "36", "38"],
    colorOptions: ["Light Gray", "Silver", "Stone"],
    fabric: "Cotton Blend",
    fitType: "Regular Fit",
    description: "Light gray trousers perfect for summer and spring seasons.",
    image: trouserImage2,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "3-4 business days",
  },
  {
    id: "trouser-9",
    name: "Burgundy Formal Pants",
    category: "Trousers",
    price: 94,
    rating: 4.7,
    sizeOptions: ["32", "34", "36"],
    colorOptions: ["Burgundy", "Wine", "Maroon"],
    fabric: "Wool Blend",
    fitType: "Slim Fit",
    description: "Bold burgundy formal pants for making a stylish statement.",
    image: trouserImage1,
    stockStatus: "Low Stock",
    brand: "MenStyle",
    deliveryTime: "3-5 business days",
  },
  {
    id: "trouser-10",
    name: "Dark Blue Jeans",
    category: "Trousers",
    price: 69,
    rating: 4.5,
    sizeOptions: ["30", "32", "34", "36", "38"],
    colorOptions: ["Dark Blue", "Black", "Light Blue"],
    fabric: "Denim",
    fitType: "Regular Fit",
    description: "Classic dark blue jeans for everyday casual wear.",
    image: trouserImage2,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "2-3 business days",
  },

  // Suits (10 products)
  {
    id: "suit-1",
    name: "Classic Black Suit",
    category: "Suits",
    price: 499,
    discountPrice: 399,
    rating: 4.9,
    sizeOptions: ["38", "40", "42", "44", "46"],
    colorOptions: ["Black", "Charcoal", "Navy"],
    fabric: "Wool Blend",
    fitType: "Slim Fit",
    description: "Timeless black suit perfect for weddings, formal events, and business occasions.",
    image: suitImage1,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "3-5 business days",
  },
  {
    id: "suit-2",
    name: "Navy Blue Business Suit",
    category: "Suits",
    price: 549,
    rating: 4.8,
    sizeOptions: ["38", "40", "42", "44"],
    colorOptions: ["Navy", "Royal Blue", "Dark Blue"],
    fabric: "Premium Wool",
    fitType: "Regular Fit",
    description: "Professional navy suit ideal for corporate settings and important meetings.",
    image: suitImage2,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "3-5 business days",
  },
  {
    id: "suit-3",
    name: "Charcoal Gray Suit",
    category: "Suits",
    price: 529,
    discountPrice: 429,
    rating: 4.7,
    sizeOptions: ["40", "42", "44", "46"],
    colorOptions: ["Charcoal", "Gray", "Dark Gray"],
    fabric: "Wool Blend",
    fitType: "Slim Fit",
    description: "Versatile charcoal suit suitable for both formal and semi-formal occasions.",
    image: suitImage1,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "3-5 business days",
  },
  {
    id: "suit-4",
    name: "Light Gray Summer Suit",
    category: "Suits",
    price: 479,
    rating: 4.6,
    sizeOptions: ["38", "40", "42", "44"],
    colorOptions: ["Light Gray", "Silver", "Dove Gray"],
    fabric: "Lightweight Wool",
    fitType: "Regular Fit",
    description: "Light gray suit perfect for summer weddings and warm-weather events.",
    image: suitImage2,
    stockStatus: "Low Stock",
    brand: "MenStyle",
    deliveryTime: "4-6 business days",
  },
  {
    id: "suit-5",
    name: "Three-Piece Suit Black",
    category: "Suits",
    price: 649,
    rating: 4.9,
    sizeOptions: ["40", "42", "44", "46"],
    colorOptions: ["Black", "Navy", "Charcoal"],
    fabric: "Premium Wool",
    fitType: "Slim Fit",
    description: "Elegant three-piece suit with vest for sophisticated formal occasions.",
    image: suitImage1,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "3-5 business days",
  },
  {
    id: "suit-6",
    name: "Pinstripe Navy Suit",
    category: "Suits",
    price: 579,
    discountPrice: 479,
    rating: 4.7,
    sizeOptions: ["38", "40", "42", "44"],
    colorOptions: ["Navy Pinstripe", "Charcoal Pinstripe", "Gray Pinstripe"],
    fabric: "Wool",
    fitType: "Regular Fit",
    description: "Classic pinstripe suit for a distinguished business appearance.",
    image: suitImage2,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "3-5 business days",
  },
  {
    id: "suit-7",
    name: "Midnight Blue Tuxedo",
    category: "Suits",
    price: 799,
    rating: 4.9,
    sizeOptions: ["38", "40", "42", "44", "46"],
    colorOptions: ["Midnight Blue", "Black"],
    fabric: "Premium Wool",
    fitType: "Slim Fit",
    description: "Luxurious midnight blue tuxedo for black-tie events and galas.",
    image: suitImage1,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "5-7 business days",
  },
  {
    id: "suit-8",
    name: "Brown Tweed Suit",
    category: "Suits",
    price: 559,
    rating: 4.6,
    sizeOptions: ["40", "42", "44"],
    colorOptions: ["Brown Tweed", "Tan Tweed", "Gray Tweed"],
    fabric: "Tweed Wool",
    fitType: "Regular Fit",
    description: "Rustic brown tweed suit perfect for country weddings and autumn events.",
    image: suitImage2,
    stockStatus: "Low Stock",
    brand: "MenStyle",
    deliveryTime: "4-6 business days",
  },
  {
    id: "suit-9",
    name: "Slim Fit Burgundy Suit",
    category: "Suits",
    price: 589,
    discountPrice: 489,
    rating: 4.7,
    sizeOptions: ["38", "40", "42", "44"],
    colorOptions: ["Burgundy", "Wine", "Deep Red"],
    fabric: "Wool Blend",
    fitType: "Slim Fit",
    description: "Bold burgundy suit for those who want to stand out at formal events.",
    image: suitImage1,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "3-5 business days",
  },
  {
    id: "suit-10",
    name: "Double-Breasted Navy Suit",
    category: "Suits",
    price: 699,
    rating: 4.8,
    sizeOptions: ["40", "42", "44", "46"],
    colorOptions: ["Navy", "Black", "Charcoal"],
    fabric: "Premium Wool",
    fitType: "Regular Fit",
    description: "Classic double-breasted navy suit for a powerful and elegant look.",
    image: suitImage2,
    stockStatus: "In Stock",
    brand: "MenStyle",
    deliveryTime: "3-5 business days",
  },
];




